[package]
name = "web_search"
version = "0.1.0"
authors = ["Saad-py <saadyarkhan11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "*"
open = "1.6.0"
